SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE timeline_relationships;
TRUNCATE TABLE timeline_items;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO timeline_items (id, title, category, category_color, note, img, img_link, description, event_date, date_label, level) VALUES
(1, 'Basic Frontend', 'Skillset', '#ffffff', 'Learnt Basic Frontend Development Skills', '/uploads/images/fe-dev.png', NULL, 'Studied HTML, CSS, JS, JQuery, Bootstrap3. Practiced in a few projects. And earned a few certificates. Expande below to learn more.', '2019-07-30', '31 Jul 2019', 0),
(2, 'Codex - My First Webpage Design', 'Task', '#ffffff', 'Developed first webpage design.', '/uploads/images/codex-first-webpage.png', 'https://youtu.be/3L_ltFz9KNU?si=K-SlXPbl5yXFNnlp', 'Made a webpage using HTML, CSS and JS. Watch video for more deails.', '2019-05-23', '24 May 2019', 1),
(3, 'HTML - Certificate', 'Skillset', '#ffffff', 'Earned HTML Certificate', '/uploads/images/html-certificate.png', 'https://www.sololearn.com/certificates/CT-R05HTXOZ', 'Learnt standards and terminologies from an online HTML course. Completed upto a verifiable certificate. Click on certificate to verify.', '2019-07-30', '31 Jul 2019', 1),
(4, 'D1 - My Second Webpage Design', 'Skillset', '#ffffff', 'Developed second webpage design.', '/uploads/images/d1-webpage.png', 'https://youtu.be/78SD6Li523k?si=p0cD7UEQ2vFJsgiF', 'Made second webpage design. Practiced paralyx, flex and box-model. Click image to watch video.', '2019-10-26', '27 Oct 2019', 1),
(5, 'Basic Programming Skills', 'Skillset', '#ffffff', 'Learnt Basic Programming Languages', '/uploads/images/c-cpp-java-py.png', NULL, 'Studied C, C++, Python, Java. Played with Processing.org sketchbook and developed some projects wortk acknowledgment.', '2019-07-26', '27 Jul 2019', 0),
(6, 'IoT - Arduino Playground', 'Skillset', '#ffffff', 'Made projects with Arduino.', '/uploads/images/arduino-modules.png', NULL, 'During my early education, I made some projects with Arduino microcontrollers for fun. Later they became my reason for selecting software engineering career.', '2019-02-14', '15 Feb 2019', 0),
(7, 'Processing.org - Software Sketchbook', 'Skillset', '#ffffff', 'I studied and made fun projects in Processing Sketchbook.', '/uploads/images/processing-org.png', 'https://processing.org', 'Practiced programming skills and developed some games with processing.org using i3, p5.js in programming languages: C++, Java, Python.', '2019-07-26', '27 Jul 2019', 1),
(8, 'C/C++ Programming', 'Skillset', '#ffffff', NULL, NULL, NULL, 'Studied C and C++ concepts, developed some projects.', '2019-04-26', '27 Apr 2019', 1),
(10, 'Qurbani App - Desktop App', 'Task', '#ffffff', 'A single-file Tkinter-based desktop-app with 2 CRUDs and MySQL database.', '/uploads/images/qurbani-app.png', 'https://youtu.be/AttFaZTN-YY?si=idSzrtJQlC-QNzkZ', 'Qurbani app is a Tkinter (python) based desktop application that allows a butcher manage their customers. It has two cruds for Nigrans (managers) and Qurbanis (Orders). It allows user to perform CRUDs on both records using mysql database Queries. It is using a MariaDB (xampp) server for database.', '2019-08-11', '12 Aug 2019', 2),
(11, 'Python Programming', 'Skillset', '#ffffff', NULL, NULL, NULL, 'Studied python and practiced tasks and short-projects.', '2019-05-21', '22 May 2019', 1),
(12, 'Calculator - Desktop App', 'Task', '#ffffff', 'Developed a Basic Calculator', '/uploads/images/processing-calculator.png', 'https://youtu.be/iTt8Qm4tHFY?si=Dt5bEpBfhunT3HjO', 'A calculator UI with event that performs basic arithmetic operations using events. using Java language (Processing.org''s Java language is more like C++).', '2019-06-21', '22 Jun 2019', 2),
(13, 'Game: Dino Game', 'Task', '#ffffff', 'Developed chrome-like dino game.', '/uploads/images/dino-game.png', 'https://youtu.be/NFhR2174Z0M?si=6W4Tl0inoHlwVhKW', 'Developed a game with boxes with same logic as that of Google Chrome browser''s offline mode dino game. Used Processing 3 Java language. Exported builds for both android (APK) and Desktop. Click image to watch video demo', '2019-07-04', '5 Jul 2019', 2),
(14, 'Game: Bounce Game', 'Task', '#ffffff', 'Developed Nokia''s bounce-like mini game.', '/uploads/images/bounce-game.png', 'https://youtu.be/bO6oBYrThj4?si=6bKibpCgE8MF_bwJ', 'Developed a game with basic shapes. Programmed logic for gravity, bouncy and acceleration of object using Python in Processnig 3. Created exports for both Desktop and Andrid. Click image to watch demo video.', '2019-07-23', '24 Jul 2019', 2),
(15, 'Game: Space Fight (2 Player)', 'Task', '#ffffff', 'Developed A space-fight like mini game.', '/uploads/images/mini-game.png', 'https://www.youtube.com/watch?v=mDhJkZqgWa8', 'Developed a game. Programmed logic for gravity, two players, scoring and shapes using Java in Processnig 3. Click to watch demo video.', '2019-04-15', '16 Apr 2019', 2),
(16, 'Game: Tank Attack (2 Player)', 'Task', '#ffffff', 'Developed A tank-attack mini game.', '/uploads/images/mini-game-2.png', 'https://youtu.be/Lqj_oAUQavQ?si=ghrVgyIXN-2k_ytm', 'Developed a game. Programmed logic for heating weapon, short random displacement of weapon for difficulity, health calculation, scoring and restart using Java in Processnig 3. Click to watch demo video.', '2019-04-15', '16 Apr 2019', 2),
(17, 'Button Press - Interval Detector', 'Task', '#ffffff', 'Press pushbutton and detect time difference..', '/uploads/images/arduino-button-interval.png', 'https://youtu.be/tsDzaF76rIo?si=yY3j0SNDCPaMAgDA', 'Click image to watch video.', '2019-02-14', '15 Feb 2019', 1),
(18, 'UI: Button Design', 'Task', '#ffffff', 'An interactive button with on-hover and on-click effects.', '/uploads/images/button-design.png', 'https://youtu.be/cW4aAMUgMzU?si=w2vzPa9BezAyfNUd', 'Designed a button in Processing 3 Java that has hover and click transitions to make it interactive. Click to watch video demo.', '2019-04-18', '19 Apr 2019', 2),
(19, 'Calculator using Tkinter', 'Task', '#ffffff', 'A desktop calculator app using GridLayout in Tkinter', '/uploads/images/tk-calculator.png', 'https://youtu.be/AttFaZTN-YY?si=idSzrtJQlC-QNzkZ', 'click video to watch demo.', '2019-05-21', '22 May 2019', 2),
(20, 'Desktop App to Manage Records', 'Task', '#ffffff', 'Developed Organization and Employees Records Management Desktop App using Tkinter and MySQL', '/uploads/images/py-records-app.png', 'https://youtu.be/m_R652Hmp7E?si=fpVlfMJXiFrpCSWR', 'click image to watch demo.', '2019-06-26', '27 Jun 2019', 2),
(21, 'Relay Module', 'Task', '#ffffff', NULL, '/uploads/images/arduino-relay-module.png', 'https://youtu.be/nmj3-YdAOqM?si=nwy2PRGgQpbYuhQ0', 'Programmed some tinker projects with Arduino Relay Module.', '2019-02-18', '19 Feb 2019', 1),
(22, 'WiFi Module', 'Task', '#ffffff', NULL, '/uploads/images/arduino-wifi.png', 'https://youtu.be/YiAqlHPJEf0?si=JvdMjyJ1xuCiDZ3s', 'Programmed some tinker projects with Arduino WiFi Module.', '2019-02-19', '20 Feb 2019', 1),
(23, 'IR Transmittor Receiver', 'Task', '#ffffff', NULL, '/uploads/images/arduino-ir.png', 'https://youtu.be/SqPKNCsuyMY?si=1uduJSchGD5vr-Vw', 'Programmed some tinker projects with Arduino IR Transmittor & Receiver Module.', '2019-02-20', '21 Feb 2019', 1),
(24, 'Temp & Humidity Sensing', 'Task', '#ffffff', NULL, '/uploads/images/arduino-temp.png', 'https://youtu.be/YT_FTCMMtvQ?si=qZz1WwVIbx4l1MiC', 'Programmed some tinker projects with Arduino Temprature and Humidity Sensor Module.', '2019-02-21', '22 Feb 2019', 1),
(25, 'Wall Following Bot', 'Task', '#ffffff', 'Ultrasonic wall-following Robot', NULL, NULL, 'Created a wall following robot using Ultrasonic module with a servo.', '2019-02-28', '01 Mar 2019', 1),
(26, 'Digital Pin Door Lock', 'Task', '#ffffff', 'Numpad and Servo based Door Lock', NULL, NULL, 'Created a door lock with a digital pin passcode entered via Numpad module and a servo to pull the string that opens door.', '2019-03-31', '01 Apr 2019', 1),
(27, 'Line-Following Robot', 'Task', '#ffffff', 'Line-Following Robot', NULL, NULL, 'A line-following robot that goes from one room to another and back to first when its button is pressed. Space to hold a glass and lightweight items.', '2019-04-30', '01 May 2019', 1),
(28, 'ATM Simulator', 'Task', '#ffffff', 'ATM Simulator in C++, simulates card ~> pin ~> withdraw, deposit, check balance ~> receipt.', '/uploads/images/atm-simulator.png', 'https://youtu.be/bok1nS1WUCE?si=ieLxAnR-LxAa_IZz', 'It is a C++ proejct that maintains its records in a text file for user balance and others. I collaborated with a friend. Click to watch video', '2019-04-26', '27 Apr 2019', 2),
(29, 'Sleep Time Analyzer', 'Task', '#ffffff', 'A desktop Tkinter app to monitor your sleep time and show analytics as a bar chart', '/uploads/images/sleep-time-analyzer.png', 'https://youtu.be/MeL4S3ikbKI?si=Lq_UIb51UTLJVJDz', 'click video to watch demo.', '2019-05-22', '23 May 2019', 2),
(30, 'Dino Game', 'Task', '#ffffff', 'A chrome-like dino game', '/uploads/images/py-dino.png', 'https://youtu.be/ybcAWnN4g58?si=2BCE9I9YRFq8HdaG', 'Developed a game with boxes with same logic as that of Google Chrome browser''s offline mode dino game. Used Tkinter''s Canvas for shapes and frames. Click video to watch demo', '2019-06-20', '21 Jun 2019', 2),
(31, 'Restourant POS', 'Task', '#ffffff', 'A POS App to calculate bill', '/uploads/images/py-pos.png', 'https://youtu.be/yaJUgFJ2pkE?si=s20S5lVu1mFeck1y', 'Developed Tkinter based python POS App. Click video to watch demo.', '2019-06-02', '03 Jun 2019', 2),
(32, 'PHP+SQL Backend', 'Skillset', '#ffffff', 'Learnt Basic Backend Development Skills', '/uploads/images/php-mysql.png', 'https://youtu.be/agIIxc9gry0?si=Wnfrd1S-KNz5RYZa', 'Studied PHP and SQL.', '2019-10-13', '14 Oct 2019', 0),
(33, 'Invoice Generator', 'Task', '#ffffff', 'Developed MySQL database web application with PHP and Xampp MySQL.', '/uploads/images/invoice-generator.png', 'https://youtu.be/78SD6Li523k?si=p0cD7UEQ2vFJsgiF', 'Skillset: PHP, HTML, CSS, JS, JQuery, SQL. Generates printable invoice and keeps track of history. Click video to watch demo.', '2019-10-13', '14 Oct 2019', 1);

INSERT INTO timeline_relationships (parent_id, child_id, sort_order) VALUES
(1, 4, 0),
(1, 3, 1),
(1, 2, 2),
(5, 7, 0),
(5, 10, 0),
(5, 12, 0),
(5, 13, 0),
(5, 14, 0),
(5, 15, 0),
(5, 16, 0),
(5, 18, 0),
(5, 19, 0),
(5, 20, 0),
(5, 28, 0),
(5, 29, 0),
(5, 30, 0),
(5, 31, 0),
(5, 11, 1),
(5, 8, 2),
(6, 27, 0),
(6, 26, 1),
(6, 25, 2),
(6, 24, 3),
(6, 23, 4),
(6, 22, 5),
(6, 21, 6),
(6, 17, 7),
(7, 14, 0),
(7, 13, 1),
(7, 12, 2),
(7, 18, 3),
(7, 16, 4),
(7, 15, 5),
(8, 28, 0),
(11, 10, 0),
(11, 20, 1),
(11, 30, 2),
(11, 31, 3),
(11, 29, 4),
(11, 19, 5),
(32, 33, 0);
